name: corefreesub
version: "0.5"
license: "GPL-2.0-or-later"
date: 2024-03-11
description: |
    A GAP Package for calculating the core-free subgroups and their faithful transitive permutation representations

authors:
    - name: Claudio Alexandre Piedade
      url: https://www.fc.up.pt/pessoas/claudio.piedade/
    - name: Manuel Delgado
      url: https://cmup.fc.up.pt/cmup/mdelgado/

maintainers:
    - name: Claudio Alexandre Piedade
      url: https://www.fc.up.pt/pessoas/claudio.piedade/
    - name: Manuel Delgado
      url: https://cmup.fc.up.pt/cmup/mdelgado/

GAP: ">= 4.11"

www: https://CAPiedade.github.io/corefreesub/
readme: README.md
packageinfo: https://CAPiedade.github.io/corefreesub/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/CAPiedade/corefreesub/releases/download/v0.5/corefreesub-0.5.tar.gz

abstract: |

status: dev
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    Faithful Transitive Permutation Representations, Core-Free subgroups, core-free.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>PD24</span>]   <b class='BibAuthor'>Piedade, C. A. and Delgado, M.</b>,
     <i class='BibTitle'>corefreesub, A GAP Package for calculating the core-free subgroups and their faithful transitive permutation representations,
             Version 0.5</i>
     (<span class='BibYear'>2024</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://CAPiedade.github.io/corefreesub/">https://CAPiedade.github.io/corefreesub/</a></span>.
    </p>
    

bibtex: |
    @misc{ corefreesub0.5,
      author =           {Piedade, C. A. and Delgado, M.},
      title =            {{corefreesub},  A  GAP  Package  for  calculating  the
                          core-free  subgroups  and  their  faithful  transitive
                          permutation representations, {V}ersion 0.5},
      month =            {Mar},
      year =             {2024},
      note =             {GAP package},
      howpublished =     {\href       {https://CAPiedade.github.io/corefreesub/}
                          {\texttt{https://CAPiedade.github.io/}\discretionary
                          {}{}{}\texttt{corefreesub/}}},
      keywords =         {Faithful   Transitive   Permutation   Representations;
                          Core-Free subgroups; core-free},
      printedkey =       {PD24}
    }

