
DeclareInfoClass( "InfoDrawFTPR" );
SetInfoLevel( InfoDrawFTPR, 1 );
#! @Chapter Drawing the Faithful Transitive Permutation Representation Graph
#! @Section Drawing functions
#!
#! One of the advantages of Faithful Transitive Permutation Representation Graph are on Groups generated by involutions, such as C-groups.
#! These graphs are very useful in the research of abstract polytopes and hypertopes, mainly called as "Schreier coset graphs" or "CPR graphs" in this area. 
#! Here we will give a function that builds this graph given a permutation group generated by involutions, a group and one of its core-free subgroups or by giving an isomorphism of the group into the symmetric group acting faithfully and transitively on its domain.
#! To use Graphviz in order to create the image file, you need to be running GAP on a Linux Environment (Windows Subsystem for Linux is supported), with graphviz installed.
#!
#! @Arguments G, filename [, layout, filetype]
#! @Arguments map , filename [, layout, filetype]
#! @Arguments H, K, filename [, layout, filetype]
#! @Returns exports both a .dot file and an image file
#! @Description
#! Given a transitive permutation group <A>G</A>, a faithful transitive permutation representation of a group <A>map</A> or a group <A>H</A> and one of its core-free subgroups <A>K</A>, the function will write a .dot file in the current path where GAP is running. 
#! If Graphviz is installed, the function will also create an image file on the current path.
#! If neither layout nor the filetype is specified, then the default layout is "neato" and the filetype is "svg".
#! The layouts can be one of the following: ["dot", "neato", "twopi", "circo", "fdp", "sfdp", "patchwork", "osage"] while the
#! filetypes can be one of the following: ["dot", "xdot", "ps", "pdf", "svg", "svgz", "png", "gif", "jpg", "jpeg", "json", "imap", "cmapx"].
#! @BeginExampleSession
#! 
#! @EndExampleSession
DeclareOperation("DotFTPRGraph", [IsPermGroup]);
DeclareOperation("DrawImageFTPRGraph", [IsPermGroup,IsString,IsString]);
DeclareOperation("TeXFTPRGraph", [IsPermGroup,IsString]);
DeclareOperation("DrawTeXFTPRGraph", [IsPermGroup,IsString]);