##########################################################################
##
#F Splash
##
## The aim of this function is to "splash" an image directly from the dot code.
## To this effect, it adds a preamble and makes a call to the Viz Splash function.
## To avoid forcing the user to install the Viz package (under development), a copy 
## of the Viz Splash function is included in the file "splash_from_viz.g" of this package
###########################################################################
DeclareInfoClass( "InfoDrawFTPR" );
SetInfoLevel( InfoDrawFTPR, 1 );
#! @Chapter Drawing the Faithful Transitive Permutation Representation Graph
#! @Section Drawing functions
#!
#! One of the advantages of Faithful Transitive Permutation Representation Graph are on Groups generated by involutions, such as C-groups.
#! These graphs are very useful in the research of abstract polytopes and hypertopes, mainly called as "Schreier coset graphs" or "CPR graphs" in this area. 
#! Here we will give a function that builds this graph given a permutation group generated by involutions, a group and one of its core-free subgroups or by giving an isomorphism of the group into the symmetric group acting faithfully and transitively on its domain.
#! To use Graphviz in order to create the image file, you need to be running GAP on a Linux Environment (Windows Subsystem for Linux is supported), with graphviz installed.
#!
#! @BeginGroup
#! @Returns a graph written in dot
#! @Description
#! Given a transitive permutation group <A>G</A>, a faithful transitive permutation representation of a group <A>map</A> or a group <A>H</A> and one of its core-free subgroups <A>K</A>, the function will output the permutation representation graph written in the language of a Dot file.
#! 
#! @BeginExampleSession
#! gap> G := SymmetricGroup(4);; H := Subgroup(G,[(1,2)]);; K := Subgroup(G,[(1,2,3)]);;
#! gap> DotFTPRGraph(G);
#! "digraph {\n1 -> 2 [label = r0];\n 2 -> 3 [label = r0];\n 3 -> 4 [label = r0];\n 4 -> 1 [label = r0];\n 1 -> 2 [label = r1,dir=none];\n }\n"
#! gap> DotFTPRGraph(G,H);
#! "digraph {\n1 -> 10 [label = r0];\n 2 -> 12 [label = r0];\n 3 -> 11 [label = r0];\n 4 -> 8 [label = r0];\n 5 -> 9 [label = r0];\n 6 -> 7 [label = r0];\n 7 -> 3 [label = r0];\n 8 -> 2 [label = r0];\n 9 -> 1 [label = r0];\n 10 -> 5 [label = r0];\n 11 -> 6 [label = r0];\n 12 -> 4 [label = r0];\n 2 -> 3 [label = r1,dir=none];\n 4 -> 7 [label = r1,dir=none];\n 5 -> 8 [label = r1,dir=none];\n 6 -> 9 [label = r1,dir=none];\n 10 -> 11 [label = r1,dir=none];\n }\n"
#! gap> Print(DotFTPRGraph(FactorCosetAction(G,K)));
#! digraph {
#! 1 -> 3 [label = r0];
#! 2 -> 4 [label = r0];
#! 3 -> 5 [label = r0];
#! 4 -> 6 [label = r0];
#! 5 -> 8 [label = r0];
#! 6 -> 7 [label = r0];
#! 7 -> 2 [label = r0];
#! 8 -> 1 [label = r0];
#! 1 -> 2 [label = r1,dir=none];
#! 3 -> 5 [label = r1,dir=none];
#! 4 -> 6 [label = r1,dir=none];
#! 7 -> 8 [label = r1,dir=none];
#! }
#! @EndExampleSession
#! @Arguments G
DeclareOperation("DotFTPRGraph", [IsPermGroup]);
#! @Arguments map
DeclareOperation("DotFTPRGraph", [IsGeneralMapping]);
#! @Arguments H, K
DeclareOperation("DotFTPRGraph", [IsGroup,IsGroup]);
#! @EndGroup


#! @Returns an image of the faithful transitive permutation representation graph
#! @Description
#! This global function takes as input the following arguments:
#! * <A>arg</A> := <A>dotstring</A>[, <A>rec</A>]
#! * <A>arg</A> := <A>G</A>[, <A>rec</A>]
#! * <A>arg</A> := <A>map</A>[,<A>rec</A>]
#! * <A>arg</A> := <A>H</A>,<A>K</A>[,<A>rec</A>]
#! Given a string of a graph in dot <A>dotstring</A>, this function will output and show an image of the graph.
#! Alternatively, a transitive permutation group <A>G</A>, a faithful transitive permutation representation of a group <A>map</A> or a group <A>H</A> and one of its core-free subgroups <A>K</A>, can be given. This will use <A>DotFTPRGraph</A> to calculate the <A>dotstring</A>.
#! Moreover, extra parameters can be given as a form of a record <A>rec</A>. The set of parameters that can be given inside a record can be found below, with information regarding their effect:
#! * <A>layout</A> - (a string) the engine that is used to calculate the layout of the vertices and edges of graph to output in the dot image (not used for TeX output). The supported layouts are "dot", "neato", "twopi", "circo", "fdp", "sfdp", "patchwork", "osage". By default "neato" is used.
#! * <A>directory</A> - (a string) the name of the folder where the dot and image files are created. By default, a temporary folder of GAP is used.
#! * <A>path</A> - (a string) the path where the directory will be created. If the directory is not specified, a folder "tmp.viz" will be created at the determined path. If no path is given, the default path is "~/". If no path nor directory is given, it will be saved in a temporary path of GAP.
#! * <A>file</A> - (a string) the name of the dot and image files created. By default, the name will be "vizpicture".
#! * <A>filetype</A> - (a string) the image file type that will be created. By default, the filetype will be "pdf".
#! * <A>viewer</A> - (a string) the name of the visualizer used to open the image. The supported ones are "evince","xpdf","xdg-open","okular", "gv", "open" (for the different System Architectures).
#! * <A>tikz</A> - (a boolean) if true, then the function will produce a TeX file, compile it to pdf and open.
#! * <A>viewtex</A> - (a boolean) if true, then the function will produce a TeX file and return the Tex file (but it will not compile and open any pdf from the TeX file).
#!
#! @BeginExampleSession
#! gap> G := SymmetricGroup(4);; H := Subgroup(G,[(1,2)]);; K := Subgroup(G,[(1,2,3)]);;
#! gap> DrawFTPRGraph(G);
#! gap> texfile := DrawFTPRGraph(G,H,rec(viewtex := true));; Print(texfile{[1..152]});
#! \documentclass{article}
#! \usepackage[x11names, svgnames, rgb]{xcolor}
#! \usepackage[utf8]{inputenc}
#! \usepackage{tikz}
#! \usetikzlibrary{snakes,arrows,shapes}
#! gap> SetInfoLevel(InfoDrawFTPR,2);
#! gap> DrawFTPRGraph(FactorCosetAction(G,K),rec(directory := "myfolder", layout := "fdp"));
#! #I  The temporary directory used is: ~/myfolder/
#!
#! @EndExampleSession
DeclareGlobalFunction("DrawFTPRGraph");

#! @Returns an image of the faithful transitive permutation representation graph
#! @Description
#! The same as <A>DrawFTPRGraph</A> with the parameter <A>viewtex := true</A>.
DeclareGlobalFunction("TeXFTPRGraph");

#! @Returns an image of the faithful transitive permutation representation graph
#! @Description
#! The same as <A>DrawFTPRGraph</A> with the parameter <A>tikz := true</A>.
DeclareGlobalFunction("DrawTeXFTPRGraph");